#!/usr/local/tools/perl/bin/perl
use strict;
use warnings;
my $debug = 0;
my $exe = (split /\//, $0)[-1];
my $Iam = $ENV{'USER'} || $ENV{'LOGNAME'};

use File::Find;

my $lib;
foreach my $arg (@ARGV)
    { $lib = $arg };
$lib = $lib || 'XML/Parser.pm';

my %modules;
find(sub { if($File::Find::name =~ m{$lib}) { $modules{$File::Find::name}++ }},
   @INC);
foreach my $mod (keys %modules) { print "$mod\n" };
exit 0;

