#!/usr/bin/perl
use strict;
use warnings;
my $debug = 0;
my $exe = (split /\//, $0)[-1];
my $Iam = $ENV{'USER'} || $ENV{'LOGNAME'};

my $prefix = 'http://devsvn.gspt.net/svn/legacy_applications/gsi-legacy-';
my @apps = qw( b2b-orderimporter-app catman store swom tools );

my $flag;
foreach my $arg (@ARGV)
    { $flag = $arg
    };
$flag = (defined($flag) && $flag =~ /^-?-?br?a?n?c?h?/)?1:0;

my $count = 0;
for my $app (@apps)
    { $app .= ($app !~ /-/)?'-webapp':'';
    if($flag)
	{  my $CMD = "/usr/bin/svn ls $prefix$app/branches";
	open(CMD,"$CMD | ") or die "$0: can't run $CMD: $!\n";
	while(my $br = <CMD>)
	    { print "$prefix$app/branches/$br";
	    $count++;
	    }; close CMD;
	}
    else { print "$prefix$app/trunk\n"; $count++ };
    };
my $what = ($flag)?'application branches':'applications';
print "-----\nThere are $count $what.\n";

exit 0;
